version: "3.5"

services:
  cacher:
    build: .
    environment:
      - DB_HOST=postgres
      - DB_NAME=aviata
      - DB_USER=aviata
      - DB_PASSWORD=12345678
    networks:
      - cheap_flights_api
    volumes:
      - .:/app

networks:
  cheap_flights_api:
    external: true
